### ISSUE TITLE
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=fr.coppernic.service.keyremapping.BIND }

### ISSUE THREAD

**Issue by marek-embiq** [Coppernic/KeyRemappingSample#1]
The example can not be run because of the old implementation in the fr.coppernic.sdk.keyremapper.cone.KeyRemap;

I get this when I try to run the example

2020-04-29 07:06:34.440 19366-19366/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.coppernic.keyremappingsample, PID: 19366
    java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.coppernic.keyremappingsample/fr.coppernic.keyremappingsample.MainActivity}: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=fr.coppernic.service.keyremapping.BIND }
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=fr.coppernic.service.keyremapping.BIND }
        at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1345)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1454)
        at android.app.ContextImpl.bindService(ContextImpl.java:1422)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
        at fr.coppernic.sdk.keyremapper.cone.KeyRemap.bindToService(KeyRemap.java:770)
        at fr.coppernic.keyremappingsample.MainActivity.onStart(MainActivity.java:139)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
        at android.app.Activity.performStart(Activity.java:6740)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2629)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6121) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by marek-embiq** [comment]
Oh, this project is not what I supposed to use for C-one^2. Sorry for the confusion.
